### ISSUE TITLE
Dependency of  http  0.12.0

### ISSUE THREAD

**Issue by pflausino** [CarnegieTechnologies/gallery_saver#105]
When I run pub get 

`Because sevenme depends on gallery_saver 2.0.3 which depends on http ^0.12.0+2, http ^0.12.0+2 is required.
So, because sevenme depends on http ^0.13.0, version solving failed.
Running "flutter pub get" in 7me.Mobile.Flutter.V2...
pub get failed (1; So, because sevenme depends on http ^0.13.0, version solving
failed.)`

i have some dependecies with http version 0.13.0 and i can`t go back 

my dependencies:
`

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dartz: ^0.9.2
  rxdart: ^0.24.1
  image_cropper: ^1.3.1
  flutter_slidable: ^0.5.7
  flutter_masked_text: ^0.8.0
  firebase_messaging: ^7.0.3
  charts_flutter: 0.10.0
  package_info: ^0.4.3
  webview_flutter: ^1.0.7
  location: ^3.0.2
  permission_handler: ^5.0.1+1
  google_maps_flutter: 2.0.1
  shimmer: ^1.1.1
  cached_network_image: ^2.2.0+1
  devicelocale: ^0.3.3
  flutter_appauth: ^0.9.2
  flutter_html: ^1.0.2
  flutter_widget_from_html_core: ^0.5.0
  flutter_launcher_icons: ^0.8.1
  connectivity: ^0.4.9+5
  image_picker: 0.7.3
  json_serializable: ^3.3.0
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.1.0 #remove after (SS uses it yet)
  path_provider: ^1.6.11
  dio: 4.0.0-beta6
  flutter_mobx: ^1.1.0+2
  flutter_modular: ^2.0.1
  hive_flutter: ^0.3.0+2
  hive: ^1.4.1+1
  intl: 0.17.0
  local_auth: 1.1.0
  lottie: ^0.4.0+1
  mobx: ^1.2.1
  url_launcher_web: ^0.1.1+6
  url_launcher: ^5.4.10
  youtube_player_flutter: ^7.0.0+3
  flutter_share: ^1.0.2+1
  mp_chart: 0.3.1
  percent_indicator: ^2.1.5
  flutter_svg: ^0.19.0
  platform: 3.0.0
  email_validator: ^1.0.6
  intl_phone_number_input: ^0.5.2+2
  flutter_cupertino_date_picker_fork: ^1.0.1
  flutter_libphonenumber: ^0.3.11
  extended_nested_scroll_view: ^2.0.0
  share: ^0.6.5+4
  qr_flutter: ^3.1.0
  gallery_saver: 2.0.3
  open_file: ^3.0.3
  firebase_dynamic_links: ^0.6.3
  firebase_analytics: ^6.3.0
  firebase_core: ^0.5.3
  blurrycontainer: ^0.0.1
  firebase_remote_config: ^0.4.3
  firebase_in_app_messaging: ^0.2.3
  expandable: ^4.1.4
  firebase_performance: ^0.4.3
  sentry_flutter: 4.0.6
  flutter_plugin_android_lifecycle: 2.0.0

  http: ^0.13.0
  http_parser: 4.0.0

dependency_overrides:
  dartx: ^0.5.0

dev_dependencies:
  build_runner: ^1.10.0
  #flutter_driver:
  #  sdk: flutter
  test: any
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  mobx_codegen: ^1.1.0
  mockito: ^4.1.1
  pedantic: ^1.8.0

`

**Comment by SirusCodes** [comment]
I have created a PR until it is merged you can override dependency as there are no broken APIs used
```yml
dependency_overrides:
  http: ^0.13.1
```

**Comment by lecicdjuro** [comment]
done

**Comment by not7anas** [comment]
hi i have the same problem , did you fix it ?
