### ISSUE TITLE
Getting Error wile compiling 

### ISSUE THREAD

**Issue by mk1107** [CarnegieTechnologies/gallery_saver#106]
I am getting Gradel error due to gallery_saver plugin

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
e: C:\Users\Asus\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (277, 35): Type mismatch: inferred type is String? but String was expected
e: C:\Users\Asus\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (280, 35): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gallery_saver:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 48s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by SamarpanCoder2002** [comment]
> I am getting Gradel error due to gallery_saver plugin
> 
> Launching lib\main.dart on Android SDK built for x86 in debug mode...
> Running Gradle task 'assembleDebug'...
> e: C:\Users\Asus\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (277, 35): Type mismatch: inferred type is String? but String was expected
> e: C:\Users\Asus\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (280, 35): Type mismatch: inferred type is String? but String was expected
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':gallery_saver:compileDebugKotlin'.
> 
> > Compilation error. See log for more details
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 48s
> Exception: Gradle task assembleDebug failed with exit code 1

Same problem here

**Comment by SamarpanCoder2002** [comment]
> I am getting Gradel error due to gallery_saver plugin
> 
> Launching lib\main.dart on Android SDK built for x86 in debug mode...
> Running Gradle task 'assembleDebug'...
> e: C:\Users\Asus\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (277, 35): Type mismatch: inferred type is String? but String was expected
> e: C:\Users\Asus\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (280, 35): Type mismatch: inferred type is String? but String was expected
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':gallery_saver:compileDebugKotlin'.
> 
> > Compilation error. See log for more details
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 48s
> Exception: Gradle task assembleDebug failed with exit code 1

@mk1107 convert compiledSDKVersion to 29..... problem will solved...... (For compiledSDKVersion = 30).... the api not updated...
