### ISSUE TITLE
Type mismatch: inferred type is String? but String was expected

### ISSUE THREAD

**Issue by prabhunath111** [CarnegieTechnologies/gallery_saver#115]
Can anyone help me out.

**Comment by tkortekaas** [comment]
I started using https://github.com/shofizone/gallery_saver. This works without having to change anything to your code. 
Just replace gallery_saver in your pubspec by:
`gallery_saver:
    git:
      url: https://github.com/shofizone/gallery_saver.git`

**Comment by prabhunath111** [comment]
@tkortekaas Thank you so much, It's working.
