### ISSUE TITLE
App failed to compile in Android

### ISSUE THREAD

**Issue by nayanbabariya95** [CarnegieTechnologies/gallery_saver#128]
With the `gallery_saver: ^2.1.0` app is unable to compile in Android. iOS is working fine in 14.6 version.</br>
![Screenshot 2021-06-19 at 11 09 28 PM](https://user-images.githubusercontent.com/63590009/122650994-922f5b80-d153-11eb-984f-6e4e4e47380e.png)

**Comment by theomkale** [comment]
same here

**Comment by ayberkcal** [comment]
same +1

**Comment by lan2000** [comment]
same +1

**Comment by medst** [comment]
same here 3

**Comment by AlbusSong** [comment]
same...

**Comment by Rukkaitto** [comment]
Same

**Comment by V-Carvalho** [comment]
same +1

**Comment by lecicdjuro** [comment]
fixed with 2.1.1
