### ISSUE TITLE
'gallery_saver/gallery_saver-Swift.h' file not found

### ISSUE THREAD

**Issue by rathinho** [CarnegieTechnologies/gallery_saver#13]
I added gallery_saver to my project, and got an error as below when building iOS app.

** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET sqflite OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/Ranyzhang/WorkSpace/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/gallery_saver-1.0.1/ios/Classes/GallerySaverPlugin.m:2:9: fatal error: 'gallery_saver/gallery_saver-Swift.h' file not found

    #import <gallery_saver/gallery_saver-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.`

**Comment by ailic88** [comment]
Try to run "pod install" in console.

**Comment by idrats** [comment]
The same error.
`pod install` did not help

**Comment by ailic88** [comment]
@idrats @rathinho Since Flutter does not support Swift by default, you'll have to create your project 
by using this command " flutter create -i swift my_app" in order to make this plugin works for iOS.

**Comment by vlada3003** [comment]
@idrats @rathinho is this still happening with the latest version of gallery saver?

**Comment by idrats** [comment]
Actually I did not remember what kind of actions helped me to solve this problem, but now I can not check if concrete this problem is solved. For me it is working

**Comment by walsha2** [comment]
Here is the solution, first you need to make sure to do what @ailic88 said, your project needs swift: https://stackoverflow.com/a/56281718

Once that is done, this is what else I noticed: this error only pops up when I do the following and start with a fresh repo:

```
git clean -xdf
<Launch VSCode or anything else and try to develop>
```

This never worked for me. So I have to make sure that I insert one extra step before I get started on development (one time):

```
git clean -xdf
flutter build ios
<Launch VSCode or anything else and try to develop>
```

This always works. Juts have to call `flutter build ios` (from command line) first which apparently triggers a `pod install` a little differently and  makes sure that those swift files get built in the right location.

Haven't looked into it enough to understand why, but this should get you passed the error and on to the fun stop... slinging code.

--------

@ailic88 Idk if you are the main developer but just thought I would pass on this data point. It was not clearly obvious this is what I had to do, nor is your comment in https://github.com/CarnegieTechnologies/gallery_saver/issues/13#issuecomment-521609402  - the docs were not that helpful either form a "set up" perspective:

https://pub.dev/documentation/gallery_saver

------

This is a good package and works exactly as expected once set up!

**Comment by ailic88** [comment]
@walsha2  Usually when this error occurred problem is that user didn't
add `use_frameworks!` in Podfile or environment is not setup properly.
Just like you've written above few cleaning fix the problem :).
Anyway thanks for feedback, we will improve our documentation.
