### ISSUE TITLE
Amdroid compilation error: was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.

### ISSUE THREAD

**Issue by mishaAe** [CarnegieTechnologies/gallery_saver#133]
Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
The class is loaded from /.gradle/caches/transforms-2/files-2.1/4b55b22db84b23a44d8b73ce89e328cd/jetified-kotlin-stdlib-1.5.20.jar!/kotlin/Unit.class

**Comment by Rukkaitto** [comment]
Same here

**Comment by iwamoto-taku** [comment]
Please check "/android/build.gradle" and change "ext.kotlin_version" to 1.5.20.
Like this
`buildscript {
    ext.kotlin_version = '1.5.20'
    repositories {
        google()
        jcenter()
    }`

**Comment by rikai-trongpq** [comment]
How to `update kotlin by Android Studio` bro?
