### ISSUE TITLE
Android SDK 30 - albumName is ignored when saving videos

### ISSUE THREAD

**Issue by m-schmailzl** [CarnegieTechnologies/gallery_saver#135]
When building for Android SDK 30, the albumName parameter of GallerySaver.saveVideo does not work.
The video is saved to the Movies-folder without any album.
GallerySaver.saveImage is working fine.

**Comment by hiolinh** [comment]
@m-schmailzl you can try add `android:requestLegacyExternalStorage="true"` to your <application> element in the manifest, it 's worked for me.

**Comment by m-schmailzl** [comment]
> @m-schmailzl you can try add `android:requestLegacyExternalStorage="true"` to your `<application>` element in the manifest, it 's worked for me.

requestLegacyExternalStorage is not available for SDK 30.
At the moment I am forced to build for SDK 29 but starting in August, Google will force SDK 30 in Google Play.

**Comment by dreampowder** [comment]
same problem here. videos saved in 'Movies' folder instead of the same folder for images. 

api level 30

**Comment by dvird** [comment]
someone know how to fix it?

**Comment by marcusvpais** [comment]
Anyone solve this to SDK 30? It's creating a "Movies" album and cannot change this. Please any update on this? Very important feature. Thank you.

**Comment by m-schmailzl** [comment]
The PR of BecoStopclub has been merged and the issue is fixed.
