### ISSUE TITLE
Version ^2.1.2 Don't work with Android 

### ISSUE THREAD

**Issue by Joldersman** [CarnegieTechnologies/gallery_saver#138]
flutter/.pub-cache/hosted/pub.dartlang.org/gallery_saver-2.1.2/android/src/main/kotlin/carnegietechnologies/gallery_saver/GallerySaverPlugin.kt: (28, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gallery_saver:compileDebugKotlin'.

**Comment by rafampessoa** [comment]
Same here...

**Comment by yjyoon-dev** [comment]
I also have the same problem

**Comment by silverTreeHouse** [comment]
I updated Kotlin version in build.gradle.
it's worked.

```
ext.kotlin_version = '1.5.21'
```

**Comment by yjyoon-dev** [comment]
@silverTreeHouse 
Thank you so much. It works!

**Comment by lecicdjuro** [comment]
seems that is fixed with https://github.com/CarnegieTechnologies/gallery_saver/issues/138#issuecomment-892315069, so i will close the issue
