### ISSUE TITLE
Plugin use a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by anchao-lu** [CarnegieTechnologies/gallery_saver#148]
Flutter 2.5.0
The plugins `gallery_saver` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.

**Comment by lecicdjuro** [comment]
That is not true. It is using v2 embeding.
