### ISSUE TITLE
android save image  java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add 

### ISSUE THREAD

**Issue by wangronghui01** [CarnegieTechnologies/gallery_saver#149]
java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'
E/AndroidRuntime(32113): 	at kotlinx.coroutines.internal.n.c(:76)
E/AndroidRuntime(32113): 	at kotlinx.coroutines.internal.o.t(:110)
E/AndroidRuntime(32113): 	at kotlinx.coroutines.internal.o.p(:91)
E/AndroidRuntime(32113): 	at kotlinx.coroutines.p0.b(:285)
E/AndroidRuntime(32113): 	at kotlinx.coroutines.g2.a.b(:26)
E/AndroidRuntime(32113): 	at kotlinx.coroutines.h0.a(:109)
E/AndroidRuntime(32113): 	at kotlinx.coroutines.a.w0(:158)
E/AndroidRuntime(32113): 	at kotlinx.coroutines.e.c(:56)
E/AndroidRuntime(32113): 	at kotlinx.coroutines.d.c(:1)
E/AndroidRuntime(32113): 	at kotlinx.coroutines.e.d(:49)
E/AndroidRuntime(32113): 	at kotlinx.coroutines.d.d(:1)
E/AndroidRuntime(32113): 	at d.a.b.j(:63)
E/AndroidRuntime(32113): 	at d.a.b.g(:45)
E/AndroidRuntime(32113): 	at d.a.c.onMethodCall(:29)
E/AndroidRuntime(32113): 	at i.a.c.a.j$a.a(:233)
E/AndroidRuntime(32113): 	at io.flutter.embedding.engine.f.b.e(:84)
E/AndroidRuntime(32113): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:865)
E/AndroidRuntime(32113): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(32113): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/AndroidRuntime(32113): 	at android.os.Looper.loop(Looper.java:176)
E/AndroidRuntime(32113): 	at android.app.ActivityThread.main(ActivityThread.java:8668)

**Comment by lecicdjuro** [comment]
try with 2.2.0
