### ISSUE TITLE
Allow saving to custom sub folder and naming image

### ISSUE THREAD

**Issue by MitchellQ** [CarnegieTechnologies/gallery_saver#21]
Hi,

Thanks for the plugin , however it would be better if you were able to use it to create a folder in the directory that you save it into.

i.e. on my phone it saves directly to `pictures` and it would be good if it could either create or have a function to create a sub directory that it uses for saving i.e. `pictures/MyApp` 

Also being able to name the saved image would be good,

**Comment by vlada3003** [comment]
It seems like a reasonable request, but we cannot commit to a date when this will be added. However, we will gladly accept any pull requests that tackle this issue.

**Comment by ailic88** [comment]
@MitchellQ storing image/video in custom folder will be added in version 1.0.5

**Comment by simar7** [comment]
+1 would love to see this!

**Comment by ailic88** [comment]
Version 1.0.5 is released.
 On Android:

 By default image will be saved at "pictures" system folder,
 and video at "movies" system folder.If user set folder name it will be
 at root external storage.
On iOS:
By default image and video will be saved at photos.
If user set folder name it will be added as new album at photos.

Folder name is added as optional param, so your current code should compile and without any
issue.
Naming image/video file is something that we probably are not going to do, at least in some near future.

**Comment by iNima** [comment]
Hi @ailic88,

Thanks for this library.
Setting album name works correctly on iOS but on Android (Pixel3) it does not create an album and it still saves photos to the default pictures folder.
What do you mean by "root external storage" in your comment above?
The library version that I'm using is 2.0.1

**Comment by Hwan-seok** [comment]
Seems not working on `gallery_saver: ^2.0.3`

**Comment by MitchellQ** [comment]
HI I have tried to implement this using both 1.0.5 and the latest version 2.0.3 and haven't been able to get this to work successfully 

This is my method signature `await GallerySaver.saveImage(_image.path, albumName: "My App");`

I have tried it and the picture still saves to Pictures; I tried to manually create the sub directory to see if that was the problem but no luck, there doesn't seem to be any reason why it fails to do this. Can anyone help, @ailic88 ?

**Comment by Hwan-seok** [comment]
Hi @MitchellQ,
Do you have alternative solution? your issue was opened almost 1.5 year ago.

**Comment by MitchellQ** [comment]
No @Hwan-seok sorry I haven't been working on solutions for this as this is for a project that has been completed.

**Comment by marcoberetta96** [comment]
The parameter `albumName` is not working yet in 2.1.0 version

**Comment by PairProgDominikaParaIstvanMunkacsi** [comment]
Adding android:requestLegacyExternalStorage="true" in AndroidManifest solved issue for me
