### ISSUE TITLE
Fetching Saved Image

### ISSUE THREAD

**Issue by zgramming** [CarnegieTechnologies/gallery_saver#24]
it's possible to fetch saved image from picture direcotry ? 
<p> I have console result like this, I dont know location path to fetch saved image with this plugin.
<img width="907" alt="image gallery saver" src="https://user-images.githubusercontent.com/38829404/66095088-758a7300-e5c0-11e9-8660-0088a3c63b3d.PNG">
<p> It's my code to save image.
```
void _testSaveImage() async {
    String path = "${Urls.BASE_API_IMAGE}/berita/${widget.gambarBerita}";
    GallerySaver.saveImage(path).then((bool success) {
      print('Success add image $path');
    }).catchError((onError) {
      print('Error add image $path');
    });
  }
```

**Comment by ailic88** [comment]
There is a problem on iOS platform since you can't directly get image path.
You can get image only via photo framework. Workaround that you can use is to cache image before store it into the gallery. For that you can use it https://pub.dev/packages/flutter_cache_manager

**Comment by zgramming** [comment]
@ailic88 so what best solution for my case ? 
I see in this [issue](https://github.com/CarnegieTechnologies/gallery_saver/issues/21) this plugin will added feature create custom folder in next version.
it's possible in next version i can get the path of image saved to fetching the image ?
Thank's

**Comment by ailic88** [comment]
Like I told you, you can use  flutter cache manager (https://pub.dev/packages/flutter_cache_manager ) plugin to create temp file and use its path.
And separately use our plugin to store image to gallery.
Also you can use image picker plugin to get stored image from gallery.
This plugin is not going to support getting path feature any time soon.
I'm going to close this issue.
