### ISSUE TITLE
Invalid argument(s): File on path is not an image.

### ISSUE THREAD

**Issue by cvetlicni** [CarnegieTechnologies/gallery_saver#27]
Hey guys. There is a problem with URLs that have query params such as facebook images firebase storage images, etc.
For image on this link:
[(https://scontent.flju2-1.fna.fbcdn.net/v/t1.0-9/71515447_2410538489194566_4191628866734784512_n.jpg?_nc_cat=1&_nc_oc=AQlh0ua3e1wQE5YN8CLL1ebDQSVhN9U-xa1k23i8dgUqMQX5apqyNxsYsWYJx65dbBM&_nc_ht=scontent.flju2-1.fna&oh=c2036dc3070d4c1fcd6b17e73c9ab6ad&oe=5E3176F8)](https://scontent.flju2-1.fna.fbcdn.net/v/t1.0-9/71515447_2410538489194566_4191628866734784512_n.jpg?_nc_cat=1&_nc_oc=AQlh0ua3e1wQE5YN8CLL1ebDQSVhN9U-xa1k23i8dgUqMQX5apqyNxsYsWYJx65dbBM&_nc_ht=scontent.flju2-1.fna&oh=c2036dc3070d4c1fcd6b17e73c9ab6ad&oe=5E3176F8)
library spews out `Unhandled Exception: Invalid argument(s): File on path is not an image.`

I didn't go too deep into debugging, but I'd say that
`bool isImage(String path) => imageFormats.contains(extension(path).toLowerCase());`
returns `false`, because `extension(path)` call doesn't handle extensions okay, when there are query params involved. :)

**Comment by jelenalecic** [comment]
@cvetlicni 

Can you try what you have suggested and make a PR?
We would be very thankful :)

**Comment by emvaized** [comment]
I can confirm, gallery_saver cannot save images from Unsplash.com for that reason.

**Comment by jok3erc0ncy30** [comment]
I am facing the same issue with firebase images any solution to the problem..

**Comment by shrijanRegmi** [comment]
@jok3erc0ncy30 
Use this instead....

https://pub.dev/packages/image_downloader
Works for any images and video. Best package ever

**Comment by marcoberetta96** [comment]
Same problem. Any update on this?

**Comment by lecicdjuro** [comment]
resolved

**Comment by donaldamadi** [comment]
Not resolved yet, I still get the error till today

**Comment by AliKhan6** [comment]
Hi, in case of Firebase images you can just add .png at the end of url and it will work out of the box.
For example: 
https://firebasestorage.googleapis.com/v0/b/framegpt-59864.appspot.com/o/Editted-images%2Fj9XwP6aaDdPNNAsOAMaEanzdmJn11683956029206804?alt=media&token=e52aa9eb-f0e2-4b17-b676-8ac6f8fb3793 
Above url will become:
https://firebasestorage.googleapis.com/v0/b/framegpt-59864.appspot.com/o/Editted-images%2Fj9XwP6aaDdPNNAsOAMaEanzdmJn11683956029206804?alt=media&token=e52aa9eb-f0e2-4b17-b676-8ac6f8fb3793.png
