### ISSUE TITLE
Optionally don't delete file after saving to gallery

### ISSUE THREAD

**Issue by gahrb** [CarnegieTechnologies/gallery_saver#28]
Add the option to not automatically delete the temporary file, or return the path of the saved file.
(For example when the file should be further used, e.g. upload to a server).

The 'not deleting'-.way seems to be easier to implement and not braking user space of the stored gallery file.

Add the optional argument "deleteFile" in 'lib/gallery_saver.dart' on line 21:
`static Future<bool> saveVideo(String path, {String albumName, bool deleteFile = false}) async {`

and 44:
`static Future<bool> saveImage(String path, {String albumName, bool deleteFile = false}) async {`

and change the if clauses on line 37 and 61:
`if (tempFile != null && deleteFile) {`

should fix this issue.

**Comment by jelenalecic** [comment]
@gahrb 

Can you make a pull request for this, with the code you suggested? 
We would be very thankful :)

**Comment by lecicdjuro** [comment]
resolved
