### ISSUE TITLE
Invoke permissions directly for android

### ISSUE THREAD

**Issue by gahrb** [CarnegieTechnologies/gallery_saver#29]
Add the correct permissions to the android manifest file, as it is done for example in the [camera package](https://github.com/flutter/plugins/blob/master/packages/camera/android/src/main/AndroidManifest.xml)

Add
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

to [android/src/main/AndroidManifest.xml](https://github.com/CarnegieTechnologies/gallery_saver/blob/master/android/src/main/AndroidManifest.xml)

**Comment by jelenalecic** [comment]
@gahrb 
Please make PR for this also!
Thank you very much :)

**Comment by lecicdjuro** [comment]
resolved
