### ISSUE TITLE
App crashes on Android when saving an image that has been saved already

### ISSUE THREAD

**Issue by JonasJuss** [CarnegieTechnologies/gallery_saver#31]
The app crashes completely, and I can not catch the exception, which is a problem.

It could make sense to allow for an optional overwrite. At the very least I should be able to catch an exception that states that an image with the given name already exists in the given album.

I get the following error output:
`
E/AndroidRuntime(16029): FATAL EXCEPTION: DefaultDispatcher-worker-1
E/AndroidRuntime(16029): Process: com.willow.willowframe.dev, PID: 16029
E/AndroidRuntime(16029): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getLastPathSegment()' on a null object reference
E/AndroidRuntime(16029): 	at android.content.ContentUris.parseId(ContentUris.java:88)
E/AndroidRuntime(16029): 	at carnegietechnologies.gallery_saver.FileUtils.insertImage(FileUtils.kt:79)
E/AndroidRuntime(16029): 	at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1$success$1.invokeSuspend(GallerySaver.kt:69)
E/AndroidRuntime(16029): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(16029): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
E/AndroidRuntime(16029): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
E/AndroidRuntime(16029): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
E/AndroidRuntime(16029): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
I/Process (16029): Sending signal. PID: 16029 SIG: 9
Lost connection to device.
`

**Comment by m-cakir** [comment]
+1

**Comment by jelenalecic** [comment]
@m-cakir @JonasJuss 

merged :)
sorry for taking this long.
