### ISSUE TITLE
FileUtils.kt perhaps has a little bug

### ISSUE THREAD

**Issue by monkingame** [CarnegieTechnologies/gallery_saver#35]
Thanks for the pretty tools.

When saving video to album(only for android, not tested under iOS yet), I found the output video is so large,and file size is 8M*n (n is 1,2,3...).
I check the source code and found a little bug in:
gallery_saver/android/src/main/kotlin/carnegietechnologies/gallery_saver/FileUtils.kt
function: insertVideo
line:264
codes:
```
while (inputStream.read(buffer) != EOF) {
    outputStream.write(buffer)
}
```
The buffer length is BUFFER_SIZE*n (1024 * 1024 * 8 * n),and outputStream write the gross data with whole buffer.
I think it should write the pure buffer instead and the codes will be:
```
var readLen = inputStream.read(buffer)
while (readLen != EOF) {
    outputStream.write(buffer, 0, readLen)
    readLen = inputStream.read(buffer)
}
```
And it works well by these codes.

Thanks for your great project gallery_saver again!

**Comment by jelenalecic** [comment]
@monkingame 

hey, thanks for using the plugin :)

can you make a PR for this?

I'm very sorry for not seeing this earlier, but we're busy working on some other projects.
sorry, again!

**Comment by lecicdjuro** [comment]
resolved
