### ISSUE TITLE
Rename Image

### ISSUE THREAD

**Issue by grazianisesana** [CarnegieTechnologies/gallery_saver#39]
How to change the name of the image ???

GallerySaver.saveImage(recordedImage.path, albumName: "Manager").then((path){};

**Comment by talatkuyuk** [comment]
I am in the same point. I want to change the filename while saving.
Could it be added one another named parametre String "newFileName" ?, then use like this:
`GallerySaver.saveImage(recordedImage.path, albumName: "Manager", newFileName: "something")`

**Comment by kamleshwebtech** [comment]
what is use of 'albumName' ??

**Comment by talatkuyuk** [comment]
@kamleshwebtech Don't you know that there is a gallery App in Android devices which can organize the  images in albums which albumName property refers.

**Comment by clragon** [comment]
this option is crucial for me.
When saving an image, I get the path from the temp folder where the image has a temp name, however saving the image with that name would be basically useless to the user. renaming the image in the temp folder would probably break my cache and copying and renaming it in the temp folder is a waste.

**Comment by clragon** [comment]
alright looks like the reason why this is not a thing is that you cannot actually name the images on iOS.
[comment in code](https://github.com/FiveDotTwelve/save_in_gallery/blob/master/lib/save_in_gallery.dart#L67)

**Comment by marcoberetta96** [comment]
is there any update on this?

**Comment by lecicdjuro** [comment]
we don't need this, please make a PR, we will do review, test and merge if everything is ok
