### ISSUE TITLE
Video file size after download is larger than original file on server

### ISSUE THREAD

**Issue by nivla360** [CarnegieTechnologies/gallery_saver#48]
Whenever I save a video from url after the download is complete I realize the file size is either doubled or tripled by 8MB. I've only seen this issue on android I haven't tested on iOS.

**Comment by safwanidrees** [comment]
Yes I also saw that issue that the default video size is 4 Mb but after saving it to the device by using this it can make 8Mb

**Comment by hyobbb** [comment]
Same problem. It always take 8MB space.

**Comment by IvanVoxo** [comment]
Same problem, original video's size is 2.5MB, after saving it's 8MB
