### ISSUE TITLE
How to get saved image path name?

### ISSUE THREAD

**Issue by KimKiHyuk** [CarnegieTechnologies/gallery_saver#49]
```
File image = await ImagePicker.pickImage(source: ImageSource.camera);
GallerySaver.saveImage("${image.path}", albumName: 'my_image_folder').then((bool result) {
                  if (result) {
                    log('image saved!');
                  }
                  else
                    log('saving image job has been failed');
                });
```

Hello there! I'm currently working with above code base. 
i wonder that how to get image path that saved in my_image_folder. 
i can get only boolean flag that result of GallerySaver.saveImage()

**is there a way to get the saved image path string?**

**Comment by jelenalecic** [comment]
You can't because, on iOS, that info is not available(as I can remember, correct me if I'm wrong),
I'm not an iOS dev :)
@KimKiHyuk

**Comment by KimKiHyuk** [comment]
@jelenalecic OK thanks a lot!

**Comment by umaqs** [comment]
Hi @jelenalecic 
I have a similar use case but only for Android. I want to open the gallery or files app so the user can see the saved video

**Comment by clragon** [comment]
would it be possible to get a `path` parameter for the callback that is always null on iOS?
Because I would like to name images in a certain way on android, even when this is not possible for iOS.

**Comment by marcoberetta96** [comment]
Is there any new way to do this?
How can apps like Whatsapp do this?

**Comment by clragon** [comment]
this is possible just fine, but only on android.
other libraries for example will return the path string on android and just null on iOS.

I am not sure why this ticket got closed.
