### ISSUE TITLE
v2.0 cannot save network image any more

### ISSUE THREAD

**Issue by satouriko** [CarnegieTechnologies/gallery_saver#52]
The readme instructs this
```dart
void _saveNetworkImage() async {
    String path =
        'https://image.shutterstock.com/image-photo/montreal-canada-july-11-2019-600w-1450023539.jpg';
    GallerySaver.saveImage(path).then((bool success) {
      setState(() {
        print('Image is saved');
      });
    });
  }
```

But once you do that, you'll get

`Invalid argument(s): File on path is not an image. `

**Comment by jelenalecic** [comment]
@rikakomoe 
@rikakomoe 

yup, it looks like this check works only for local files.
I haven't had enough time to test this.

I'll revert this commit.

**Comment by jelenalecic** [comment]
@rikakomoe 
try 2.0.1

**Comment by abdullah432** [comment]
Firebase image is not getting downloaded with any version

> @rikakomoe
> try 2.0.1
