### ISSUE TITLE
Great package, but it won't save images from a path that doesn't include a file extension.

### ISSUE THREAD

**Issue by ZacharyEilers** [CarnegieTechnologies/gallery_saver#56]
Really great package with a concise API. There's a big problem, however. This package won't download any image from a package that doesn't end with a supported file extension. The problem? URLs from many different places don't have the file extension. That error makes this package unusable for many, many use cases, including firebase.

You should allow the package user to specify their own request future. This would mean that you could still control the file extension that the package downloads, but also allow the user to request from a URL that doesn't contain an extension if necessary. Cheers!

**Comment by jelenalecic** [comment]
Hey @ZacharyEilers :)

Can you make a pull request for this?

**Comment by ZacharyEilers** [comment]
Yes. I’ll get to it within the next 7 days.

**Comment by cookmscott** [comment]
@ZacharyEilers Providing a small bump on this to see if this is still in scope to get fixed soon. Thank you!

I believe this roles up into the same issue as [Issue 57](https://github.com/CarnegieTechnologies/gallery_saver/issues/57)
