### ISSUE TITLE
File on path is not a video

### ISSUE THREAD

**Issue by Gursewak-Uppal** [CarnegieTechnologies/gallery_saver#57]
Not Working with Firebase MP4 file. It gives me error.

[Video URL](https://firebasestorage.googleapis.com/v0/b/pixz-92afa.appspot.com/o/PostVideos%2F0xb159d1586689312896%2F0xb159d15866893128961586846213136_video?alt=media&token=af6b076b-405e-4763-abb4-69a83f92d15b)

    E/flutter ( 9221): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): File on path is not a video.
    E/flutter ( 9221): #0      GallerySaver.saveVideo (package:gallery_saver/gallery_saver.dart:27:7)
    E/flutter ( 9221): #1      _OptionSelectionState.saveToLocale (package:pixz_app/ui/widgets/options_view.dart:618:22)
    E/flutter ( 9221): <asynchronous suspension>
    E/flutter ( 9221): #2      _OptionSelectionState.currentUserPost.<anonymous closure> (package:pixz_app/ui/widgets/options_view.dart:193:15)
    E/flutter ( 9221): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
    E/flutter ( 9221): #4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
    E/flutter ( 9221): #5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
    E/flutter ( 9221): #6      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
    E/flutter ( 9221): #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
    E/flutter ( 9221): #8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
    E/flutter ( 9221): #9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
    E/flutter ( 9221): #10     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
    E/flutter ( 9221): #11     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
    E/flutter ( 9221): #12     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
    E/flutter ( 9221): #13     _rootRunUnary (dart:async/zone.dart:1138:13)
    E/flutter ( 9221): #14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    E/flutter ( 9221): #15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
    E/flutter ( 9221): #16     _invoke1 (dart:ui/hooks.dart:273:10)
    E/flutter ( 9221): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
    E/flutter ( 9221):

**Comment by shrijanRegmi** [comment]
Same problem
I am facing that too when I try to save video from firebase storage

**Comment by kostov** [comment]
Failed to save an .ts-file -- exception: "Invalid argument(s): File on path is not a video."
Why?
