### ISSUE TITLE
Can't save file on Android and app crashed

### ISSUE THREAD

**Issue by zhaoyi0113** [CarnegieTechnologies/gallery_saver#58]
I have below code:

```
try {
      var image = await ImagePicker.pickImage(source: ImageSource.camera);
      var path = GallerySaver.saveImage(image.path);
      developer.log('path $path');
    } catch (err) {
      developer.log('failed to take photo', error: err);
    }
```
and app crashed on `GallerySaver.saveImage(image.path);`. The error I got is:

```
E/AndroidRuntime(17754): FATAL EXCEPTION: main
E/AndroidRuntime(17754): Process: com.example.rent_exp_app, PID: 17754
E/AndroidRuntime(17754): android.database.sqlite.SQLiteException: table thumbnails has no column named relative_path (code 1 SQLITE_ERROR): , while compiling: INSERT INTO thumbnails (height,image_id,kind,_data,width,relative_path) VALUES (?,?,?,?,?,?)
E/AndroidRuntime(17754): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
E/AndroidRuntime(17754): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:141)
E/AndroidRuntime(17754): 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
E/AndroidRuntime(17754): 	at android.content.ContentResolver.insert(ContentResolver.java:2083)
E/AndroidRuntime(17754): 	at android.content.ContentResolver.insert(ContentResolver.java:2045)
```

It seems that it failed to save thumbnails to SQLite database.

**Comment by honkevin** [comment]
Same issue here. iOS works perfectly.

W/MediaStore( 6096): Failed to obtain thumbnail for content://media/external/images/media/9590
W/MediaStore( 6096): java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
W/MediaStore( 6096): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
W/MediaStore( 6096): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:719)
W/MediaStore( 6096): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1705)
W/MediaStore( 6096): 	at android.content.ContentResolver.openTypedAssetFile(ContentResolver.java:1610)
W/MediaStore( 6096): 	at android.content.ContentResolver.lambda$loadThumbnail$0(ContentResolver.java:3636)
W/MediaStore( 6096): 	at android.content.-$$Lambda$ContentResolver$7ILY1SWNxC2xhk-fQUG6tAXW9Ik.call(Unknown Source:10)
W/MediaStore( 6096): 	at android.graphics.ImageDecoder$CallableSource.createImageDecoder(ImageDecoder.java:550)
W/MediaStore( 6096): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1847)
W/MediaStore( 6096): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1840)
W/MediaStore( 6096): 	at android.content.ContentResolver.loadThumbnail(ContentResolver.java:3635)
W/MediaStore( 6096): 	at android.content.ContentResolver.loadThumbnail(ContentResolver.java:3619)
W/MediaStore( 6096): 	at android.provider.MediaStore$InternalThumbnails.getThumbnail(MediaStore.java:1601)
W/MediaStore( 6096): 	at android.provider.MediaStore$Images$Thumbnails.getThumbnail(MediaStore.java:1960)
W/MediaStore( 6096): 	at carnegietechnologies.gallery_saver.FileUtils.insertImage(FileUtils.kt:81)
W/MediaStore( 6096): 	at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1$success$1.invokeSuspend(GallerySaver.kt:69)
W/MediaStore( 6096): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/MediaStore( 6096): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)

**Comment by stepanov-standy** [comment]
+1 I see the same issue only on Android 11 Beta 2 (Pixel 3a). 

```
E/AndroidRuntime(18765): java.lang.IllegalArgumentException: Invalid column NULL
E/AndroidRuntime(18765): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
E/AndroidRuntime(18765): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
E/AndroidRuntime(18765): 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
E/AndroidRuntime(18765): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1809)
E/AndroidRuntime(18765): 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1515)
E/AndroidRuntime(18765): 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1491)
E/AndroidRuntime(18765): 	at carnegietechnologies.gallery_saver.FileUtils.storeThumbnail(FileUtils.kt:172)
E/AndroidRuntime(18765): 	at carnegietechnologies.gallery_saver.FileUtils.insertImage(FileUtils.kt:84)
E/AndroidRuntime(18765): 	at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1$success$1.invokeSuspend(GallerySaver.kt:69)
E/AndroidRuntime(18765): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(18765): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
E/AndroidRuntime(18765): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
E/AndroidRuntime(18765): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
E/AndroidRuntime(18765): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by stepanov-standy** [comment]
Any updates on this issue? Looks like we have to disable save to gallery functionality on Android 11 until the fix is introduced.

**Comment by CircleOnCircles** [comment]
> +1 I see the same issue only on Android 11 Beta 2 (Pixel 3a).
> 
> ```
> E/AndroidRuntime(18765): java.lang.IllegalArgumentException: Invalid column NULL
> E/AndroidRuntime(18765): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
> E/AndroidRuntime(18765): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
> E/AndroidRuntime(18765): 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
> E/AndroidRuntime(18765): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1809)
> E/AndroidRuntime(18765): 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1515)
> E/AndroidRuntime(18765): 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1491)
> E/AndroidRuntime(18765): 	at carnegietechnologies.gallery_saver.FileUtils.storeThumbnail(FileUtils.kt:172)
> E/AndroidRuntime(18765): 	at carnegietechnologies.gallery_saver.FileUtils.insertImage(FileUtils.kt:84)
> E/AndroidRuntime(18765): 	at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1$success$1.invokeSuspend(GallerySaver.kt:69)
> E/AndroidRuntime(18765): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> E/AndroidRuntime(18765): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
> E/AndroidRuntime(18765): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
> E/AndroidRuntime(18765): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
> E/AndroidRuntime(18765): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
> ```

+1 Pixel 3 API 30 Android 10+

```
E/AndroidRuntime(12402): java.lang.IllegalArgumentException: Invalid column NULL
E/AndroidRuntime(12402): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
E/AndroidRuntime(12402): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
E/AndroidRuntime(12402): 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
E/AndroidRuntime(12402): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1809)
E/AndroidRuntime(12402): 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1515)
E/AndroidRuntime(12402): 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1491)
E/AndroidRuntime(12402): 	at carnegietechnologies.gallery_saver.FileUtils.storeThumbnail(FileUtils.kt:172)
E/AndroidRuntime(12402): 	at carnegietechnologies.gallery_saver.FileUtils.insertImage(FileUtils.kt:84)
E/AndroidRuntime(12402): 	at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1$success$1.invokeSuspend(GallerySaver.kt:69)
E/AndroidRuntime(12402): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(12402): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
E/AndroidRuntime(12402): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
E/AndroidRuntime(12402): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
E/AndroidRuntime(12402): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
I/Process (12402): Sending signal. PID: 12402 SIG: 9
Failed to send request: {"jsonrpc":"2.0","id":"172","method":"resume","params":{"isolateId":"isolates/586635803018715"}}
```

**Comment by dufei816** [comment]
GallerySaver.saveImage(path)

``W/MediaStore(25453): Failed to obtain thumbnail for content://media/external/images/media/700621
W/MediaStore(25453): java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
W/MediaStore(25453): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
W/MediaStore(25453): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
W/MediaStore(25453): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1702)
W/MediaStore(25453): 	at android.content.ContentResolver.openTypedAssetFile(ContentResolver.java:1607)
W/MediaStore(25453): 	at android.content.ContentResolver.lambda$loadThumbnail$0(ContentResolver.java:3617)
W/MediaStore(25453): 	at android.content.-$$Lambda$ContentResolver$7ILY1SWNxC2xhk-fQUG6tAXW9Ik.call(Unknown Source:10)
W/MediaStore(25453): 	at android.graphics.ImageDecoder$CallableSource.createImageDecoder(ImageDecoder.java:550)
W/MediaStore(25453): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1847)
W/MediaStore(25453): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1840)
W/MediaStore(25453): 	at android.content.ContentResolver.loadThumbnail(ContentResolver.java:3616)
W/MediaStore(25453): 	at android.content.ContentResolver.loadThumbnail(ContentResolver.java:3600)
W/MediaStore(25453): 	at android.provider.MediaStore$InternalThumbnails.getThumbnail(MediaStore.java:1568)
W/MediaStore(25453): 	at android.provider.MediaStore$Images$Thumbnails.getThumbnail(MediaStore.java:1927)
W/MediaStore(25453): 	at carnegietechnologies.gallery_saver.FileUtils.insertImage(FileUtils.kt:81)
W/MediaStore(25453): 	at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1$success$1.invokeSuspend(GallerySaver.kt:69)
W/MediaStore(25453): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/MediaStore(25453): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
W/MediaStore(25453): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
W/MediaStore(25453): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
W/MediaStore(25453): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by Nillouise** [comment]
Same issue, but I have successful in other environment.

**Comment by mr-techiee** [comment]
> Same issue here. iOS works perfectly.
> 
> W/MediaStore( 6096): Failed to obtain thumbnail for content://media/external/images/media/9590
> W/MediaStore( 6096): java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
> W/MediaStore( 6096): at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
> W/MediaStore( 6096): at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:719)
> W/MediaStore( 6096): at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1705)
> W/MediaStore( 6096): at android.content.ContentResolver.openTypedAssetFile(ContentResolver.java:1610)
> W/MediaStore( 6096): at android.content.ContentResolver.lambda$loadThumbnail$0(ContentResolver.java:3636)
> W/MediaStore( 6096): at android.content.-$$Lambda$ContentResolver$7ILY1SWNxC2xhk-fQUG6tAXW9Ik.call(Unknown Source:10)
> W/MediaStore( 6096): at android.graphics.ImageDecoder$CallableSource.createImageDecoder(ImageDecoder.java:550)
> W/MediaStore( 6096): at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1847)
> W/MediaStore( 6096): at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1840)
> W/MediaStore( 6096): at android.content.ContentResolver.loadThumbnail(ContentResolver.java:3635)
> W/MediaStore( 6096): at android.content.ContentResolver.loadThumbnail(ContentResolver.java:3619)
> W/MediaStore( 6096): at android.provider.MediaStore$InternalThumbnails.getThumbnail(MediaStore.java:1601)
> W/MediaStore( 6096): at android.provider.MediaStore$Images$Thumbnails.getThumbnail(MediaStore.java:1960)
> W/MediaStore( 6096): at carnegietechnologies.gallery_saver.FileUtils.insertImage(FileUtils.kt:81)
> W/MediaStore( 6096): at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1$success$1.invokeSuspend(GallerySaver.kt:69)
> W/MediaStore( 6096): at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> W/MediaStore( 6096): at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)

**Comment by jelenalecic** [comment]
please try the newest version of the gallery_saver. thanks :)
