### ISSUE TITLE
Command CompileSwiftSources failed with a nonzero exit code (in target 'gallery_saver' from project 'Pods')

### ISSUE THREAD

**Issue by shylaharild** [CarnegieTechnologies/gallery_saver#59]
I am facing this issue with the 'gallery_saver' when I tried to build my Flutter app for iOS. I can run the app on my simulator or local devices for testing purposes. When I try to build a release version for the app, this error pops up at the Archive Build/Analyze stage in the XCode.

**Error**
`CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'gallery_saver' from project 'Pods')
    cd /Users/appuser/codeBase/flutter/ios/Pods
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk
    export TOOLCHAINS="org.swift.30220161213a "
    /Library/Developer/Toolchains/swift-3.0.2-RELEASE.xctoolchain/usr/bin/swiftc -incremental -module-name gallery_saver -Onone -enable-batch-mode -enforce-exclusivity=checked @/Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gallery_saver.build/Objects-normal/armv7/gallery_saver.SwiftFileList -DDEBUG -D COCOAPODS -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk -target armv7-apple-ios8.0 -g -module-cache-path /Users/appuser/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -enable-testing -index-store-path /Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Index/DataStore -swift-version 5 -I /Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Products/Debug-iphoneos/gallery_saver -F /Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Products/Debug-iphoneos/gallery_saver -F /Users/appuser/codeBase/flutter/ios/Flutter -parse-as-library -c -j4 -output-file-map /Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gallery_saver.build/Objects-normal/armv7/gallery_saver-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gallery_saver.build/Objects-normal/armv7/gallery_saver.swiftmodule -Xcc -I/Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gallery_saver.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gallery_saver.build/gallery_saver-generated-files.hmap -Xcc -I/Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gallery_saver.build/gallery_saver-own-target-headers.hmap -Xcc -I/Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gallery_saver.build/gallery_saver-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gallery_saver.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gallery_saver.build/gallery_saver-project-headers.hmap -Xcc -I/Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Products/Debug-iphoneos/gallery_saver/include -Xcc -I/Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gallery_saver.build/DerivedSources-normal/armv7 -Xcc -I/Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gallery_saver.build/DerivedSources/armv7 -Xcc -I/Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gallery_saver.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -emit-objc-header -emit-objc-header-path /Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gallery_saver.build/Objects-normal/armv7/gallery_saver-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/appuser/Library/Developer/Xcode/DerivedData/Runner-bsbtyadcgnorhndshclbxpflcqxv/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gallery_saver.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/appuser/codeBase/flutter/ios/Pods

<unknown>:0: error: unknown argument: '-enable-batch-mode'
<unknown>:0: error: unknown argument: '-enforce-exclusivity=checked'
<unknown>:0: error: unknown argument: '-index-store-path'
<unknown>:0: error: unknown argument: '-swift-version'
Command CompileSwiftSources failed with a nonzero exit code`

**Comment by MrLiuYS** [comment]
try again

```
  gallery_saver:
    git:
      url: https://github.com/MrLiuYS/gallery_saver.git
      ref: oc
```
