### ISSUE TITLE
saveVideo() not saving videos into albums

### ISSUE THREAD

**Issue by UnicornsOnLSD** [CarnegieTechnologies/gallery_saver#63]
I'm using the following function to save a video:
```dart
await GallerySaver.saveVideo("${temporaryPath.path}/output.mp4",
        albumName: "TimeLapseApp");
```
To my knowledge, this should save to the TimeLapseApp album (note that this is a new album). The video is being saved into the Movies album (Movies folder on Android).

![image](https://user-images.githubusercontent.com/44349936/87166004-d3bc5300-c2c2-11ea-9972-c71656549034.png)

**Comment by kamleshwebtech** [comment]
any solution ??

**Comment by hyobbb** [comment]
I have the same issue. I think it should create the new album if the argument is given.

**Comment by emilygeorg** [comment]
I am having this issue as well but my video is not being saved to any album, not even Recents.
