### ISSUE TITLE
Cannot download image/video from firebase storage

### ISSUE THREAD

**Issue by alihaider78222** [CarnegieTechnologies/gallery_saver#66]
Here is an example of image link i tried to download and its generating error on this similar links "https://firebasestorage.googleapis.com/v0/b/eventat-4ba96.appspot.com/o/2019-Metrology-Events.jpg?alt=media&token=bfc47032-5173-4b3f-86bb-9659f46b362a"

**Comment by benlove** [comment]
This is an easy one to fix, but I can't figure out how to do a pull request. in lib/files.dart the isVideo and isImage functions use the extension method and this doesn't recognize extensions that are inline in the URL string. The quickest way to fix this is by removing the existing isVideo and isFile functions in lib/files.dart and replace them with:

```
bool isVideo(String path) {
  bool output = false;
  videoFormats.forEach((videoFormat) {
    if (path.toLowerCase().contains(videoFormat)) output = true;
  });
  return output;
}

bool isImage(String path) {
  bool output = false;
  imageFormats.forEach((imageFormat) {
    if (path.toLowerCase().contains(imageFormat)) output = true;
  });
  return output;
}
```

**Comment by alihaider78222** [comment]
i'll try this solution, thanks for you help, i really appreciate that :) 👍

**Comment by ismailgungor** [comment]
Hi, I fix it by adding ".png" or ".jpg" to end of the firebase url.
Here you can see the example:
`var currentUrl = "${viewModel.currentWallpaper.url}.png";
GallerySaver.saveImage(currentUrl);`

**Comment by Itsnishant4** [comment]
https://cdn.jsdelivr.net/gh/Itsnishant4/images/images/2026/03/1774496317364-2019-Metrology-Events.jpg 


got your image on this url ✳️

i stuck on same issu then i got my video and also then try to got your image and i got it 😁
