### ISSUE TITLE
Android - App crashes when I try to save an image

### ISSUE THREAD

**Issue by marcobraghim** [CarnegieTechnologies/gallery_saver#70]
I don't know what kind of information is useful at this time to fix this, please, let me know.

app/build.gradle
android.compileSdkVersion 28
android.defaultConfig.inSdkVersion 24
android.defaultConfig.targetSdkVersion 28

Permission granted in
android.permission.WRITE_EXTERNAL_STORAGE

```
E/AndroidRuntime(  849): android.database.sqlite.SQLiteException: table thumbnails has no column named relative_path (code 1 SQLITE_ERROR): , while compiling: INSERT INTO thumbnails (height,image_id,kind,_data,width,relative_path) VALUES (?,?,?,?,?,?)
E/AndroidRuntime(  849): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
E/AndroidRuntime(  849): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
E/AndroidRuntime(  849): 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
E/AndroidRuntime(  849): 	at android.content.ContentResolver.insert(ContentResolver.java:2045)
E/AndroidRuntime(  849): 	at android.content.ContentResolver.insert(ContentResolver.java:2007)
E/AndroidRuntime(  849): 	at carnegietechnologies.gallery_saver.FileUtils.storeThumbnail(FileUtils.kt:165)
E/AndroidRuntime(  849): 	at carnegietechnologies.gallery_saver.FileUtils.insertImage(FileUtils.kt:84)
E/AndroidRuntime(  849): 	at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1$success$1.invokeSuspend(GallerySaver.kt:69)
E/AndroidRuntime(  849): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(  849): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
E/AndroidRuntime(  849): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
E/AndroidRuntime(  849): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
E/AndroidRuntime(  849): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
I/Process (  849): Sending signal. PID: 849 SIG: 9
Lost connection to device.
```

**Comment by marcobraghim** [comment]
Approving PR #67 will fix it (workaround, actually)

**Comment by novas1r1** [comment]
Same crash for Pixel 2 with Android 11

**Comment by rogiervandenberg** [comment]
Same on Pixel 3 with Android 11

**Comment by muhammedEmir06** [comment]
same issue and it's not fixed yet

**Comment by marcobraghim** [comment]
Hey guys, to handle this issue you should use the [permission_handler](https://pub.dev/packages/permission_handler) package asking for permission before save something to device.

**Comment by muhammedEmir06** [comment]
@marcobraghim Unfortunately your solution is not working on Android 10 Api 29.

**Comment by marcobraghim** [comment]
> @marcobraghim Unfortunately your solution is not working on Android 10

It is working for me on Android 10 with another package [image_gallery_saver](https://pub.dev/packages/image_gallery_saver). Hope it helps you

**Comment by muhammedEmir06** [comment]
thank you

**Comment by novas1r1** [comment]
For me the image_gallery_saver is also not working on Android 11

**Comment by VOIDCRUSHER** [comment]
@marcobraghim  I'm encountering this issue now as well. Was your final solution to migrate functionality to another package, image_gallery_saver?

**Comment by novas1r1** [comment]
@VOIDCRUSHER Android works fine with the "image_gallery_saver" button iOS doesnt even build. If you only need Android its fine, if you need both you will not be able to use the packe with iOS. I didnt find ANY solution on saving images on Android and iOS at the moment.

**Comment by marcobraghim** [comment]
For now that other package is doing the work. Hope this one to be better soon...

**Comment by VOIDCRUSHER** [comment]
@marcobraghim Would we not want to keep this issue open? It seems to common to many users and hasn't been resolved by the maintainers.
