### ISSUE TITLE
gallery_saver: ^2.0.1 and workmanager: ^0.2.3 don't work together.

### ISSUE THREAD

**Issue by AhmetMelihSerter** [CarnegieTechnologies/gallery_saver#72]
I am using **gallery_saver: ^2.0.1** and **workmanager: ^0.2.3** packages but they don't work together. 
This error occurs when i add **pubspec.yaml** to **gallery_saver: ^2.0.1**. 

Error:
**Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@7eaf22b) but could not find and invoke the GeneratedPluginRegistrant.**

**Comment by 2math** [comment]
My workaround is to override the GallerySaverPlugin and put one simple try catch. 
I really hope the owner of the plugin will do that as well, because that plugin brakes the registration of all plugins if is called from isolate, because it requires activity.

companion object {
        @JvmStatic
        fun registerWith(registrar: Registrar) {
            try {
                val channel = MethodChannel(registrar.messenger(),
                        "gallery_saver")
                val gallerySaver = GallerySaver(registrar.activity())
                registrar.addRequestPermissionsResultListener(gallerySaver)
                val instance = GallerySaverPlugin(
                        gallerySaver)
                channel.setMethodCallHandler(instance)
            } catch (e: Exception) {
//                Log.e("register gallery_saver", e)
            }
        }
    }

**Comment by AhmetMelihSerter** [comment]
> My workaround is to override the GallerySaverPlugin and put one simple try catch.
> I really hope the owner of the plugin will do that as well, because that plugin brakes the registration of all plugins if is called from isolate, because it requires activity.
> 
> ```
> companion object {
>         @JvmStatic
>         fun registerWith(registrar: Registrar) {
>             try {
>                 val channel = MethodChannel(registrar.messenger(),
>                         "gallery_saver")
>                 val gallerySaver = GallerySaver(registrar.activity())
>                 registrar.addRequestPermissionsResultListener(gallerySaver)
>                 val instance = GallerySaverPlugin(
>                         gallerySaver)
>                 channel.setMethodCallHandler(instance)
>             } catch (e: Exception) {
> //                Log.e("register gallery_saver", e)
>             }
>         }
>     }
> ```

I solved it by updating the package to 2.0.3. 👍

**Comment by lecicdjuro** [comment]
fixed
