### ISSUE TITLE
Getting "File on path is not an image" when try to download the image url which has query parameters

### ISSUE THREAD

**Issue by sureace** [CarnegieTechnologies/gallery_saver#73]
Hi 
     when try to download the image url which has query parameters after extension. 
Ex: https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx/o/service%2Fimage_picker1766734803341919810.jpg?alt=media&token=be15927c-8bd3-4ec6-9686-0e1016bcd89e

Thanks

**Comment by kodi** [comment]
same here

**Comment by abdullah432** [comment]
same
