### ISSUE TITLE
Does not compile on android in app with `compileSdkVersion 30`

### ISSUE THREAD

**Issue by bulwinkel** [CarnegieTechnologies/gallery_saver#75]
Due to additional nullability annotations added to the android framework in API level 30 this plugin does not compile when included in an app targeting `compileSdkVersion 30`.

This can be fixed with a few small changes in `FileUtils.kt` to provide default values for potential nulls in some log statements.

To replicate update the `compileSdkVersion` to 30 in the example project and attempt to build.

**Comment by jelenalecic** [comment]
please try the newest version :)

**Comment by MakeshVineeth** [comment]
> please try the newest version :)

Hello, I've tried the latest version `^2.0.2`, However I'm still facing the similar compilation issues with `compileSdkVersion 30`.

Following are the two errors I get during gradle build:

`e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-2.0.2\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (275, 35): Type mismatch: inferred type is String? but String was expected`

`e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-2.0.2\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (278, 35): Type mismatch: inferred type is String? but String was expected`

On a safe side, I also tried the following steps and yet no profit:

- Remove gallery_saver from pubspec.yaml
- flutter clean
- Delete gallery_saver related folders from pub-cache.
- Add the package again.

**Comment by karabanovbs** [comment]
> > please try the newest version :)
> 
> Hello, I've tried the latest version `^2.0.2`, However I'm still facing the similar compilation issues with `compileSdkVersion 30`.
> 
> Following are the two errors I get during gradle build:
> 
> `e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-2.0.2\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (275, 35): Type mismatch: inferred type is String? but String was expected`
> 
> `e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-2.0.2\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (278, 35): Type mismatch: inferred type is String? but String was expected`
> 
> On a safe side, I also tried the following steps and yet no profit:
> 
> * Remove gallery_saver from pubspec.yaml
> * flutter clean
> * Delete gallery_saver related folders from pub-cache.
> * Add the package again.

The same problem

**Comment by karabanovbs** [comment]
@jelenalecic

**Comment by chrisedg87** [comment]
Also seeing this issue with 2.0.3. Could we re-open?
