### ISSUE TITLE
Can i save network image using this plugin?

### ISSUE THREAD

**Issue by Purelightme** [CarnegieTechnologies/gallery_saver#8]
When i pass a network image url to GallerySaver.saveImage method,the app crashed and throw an exception:java.io.FileNotFoundException.
Can you support network image save?
thank you.

**Comment by ailic88** [comment]
This feature will be added in next version, which will be released by the end of this week.

**Comment by jelenalecic** [comment]
@Purelightme 
Thanks for your feedback.
Please check 1.0.0 version and let us know if you have any issues with it :)

**Comment by Purelightme** [comment]
> @Purelightme
> Thanks for your feedback.
> Please check 1.0.0 version and let us know if you have any issues with it :)

Fantastic,i saved a network image into my android gallery successfully.
