### ISSUE TITLE
GallerySaver.saveImage crashes on Android 11.0 

### ISSUE THREAD

**Issue by crossplatfrom** [CarnegieTechnologies/gallery_saver#85]
Devices: Pixel 4 XL, Pixel 5 XL
Device Type: Virtual & Physical
Android Version: 11.0 API 30

An exception and crash occurs upon calling `GallerySaver.saveImage` however, the image DOES get saved to the gallery successfully. The app simply crashes at this point. Tested also on Android 10.0 on both devices and the crash does not happen.

`E/AndroidRuntime(20767): java.lang.IllegalArgumentException: Invalid column NULL`
`E/AndroidRuntime(20767): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)`
`E/AndroidRuntime(20767): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)`
`E/AndroidRuntime(20767): 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)`
`E/AndroidRuntime(20767): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1816)`
`E/AndroidRuntime(20767): 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1518)`
`E/AndroidRuntime(20767): 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1494)`
`E/AndroidRuntime(20767): 	at carnegietechnologies.gallery_saver.FileUtils.storeThumbnail(FileUtils.kt:172)`
`E/AndroidRuntime(20767): 	at carnegietechnologies.gallery_saver.FileUtils.insertImage(FileUtils.kt:84)`
`E/AndroidRuntime(20767): 	at carnegietechnologies.gallery_saver.GallerySaver$saveMediaFile$1$success$1.invokeSuspend(GallerySaver.kt:69)`
`E/AndroidRuntime(20767): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)`
`E/AndroidRuntime(20767): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)`
`E/AndroidRuntime(20767): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)`
`E/AndroidRuntime(20767): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)`
`E/AndroidRuntime(20767): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)`

**Comment by VOIDCRUSHER** [comment]
I can confirm the same behavior on Android API 29+. I was able to test on API 28 and that worked fine. The image does save to the gallery successfully but crashes the app.

```
E/AndroidRuntime(10136): Process: com.*.app, PID: 10136
E/AndroidRuntime(10136): java.lang.IllegalArgumentException: Invalid column NULL
E/AndroidRuntime(10136): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
E/AndroidRuntime(10136): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
E/AndroidRuntime(10136): 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
E/AndroidRuntime(10136): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1816)
E/AndroidRuntime(10136): 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1518)
E/AndroidRuntime(10136): 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1494)
E/AndroidRuntime(10136): 	at c.a.a.a(:172)
E/AndroidRuntime(10136): 	at c.a.a.a(:84)
E/AndroidRuntime(10136): 	at c.a.b$b$a.b(:69)
E/AndroidRuntime(10136): 	at h.x.j.a.a.a(:33)
E/AndroidRuntime(10136): 	at kotlinx.coroutines.r0.run(:238)
E/AndroidRuntime(10136): 	at kotlinx.coroutines.f2.a.a(:594)
E/AndroidRuntime(10136): 	at kotlinx.coroutines.f2.a.a(:60)
E/AndroidRuntime(10136): 	at kotlinx.coroutines.f2.a$b.run(:742)
I/Process (10136): Sending signal. PID: 10136 SIG: 9
```

This issue appears related to #58, #69 and possibly #47, #75

**Comment by nick-named** [comment]
Happens to me as well

**Comment by ninjaasmoke** [comment]
Hey, a temporary solution could be to put the code that saves your image in a try catch block and simply continue with the flow. Just a suggestion for now

**Comment by dancamdev** [comment]
Happens to me as well, has someone managed to fix it? Did you find any alternatives that work on Android 11?

**Comment by Hashpurple** [comment]
Happens to me as well

**Comment by realjdragon** [comment]
Happens to me as well!!!!!!!!

**Comment by iamsandeepsk** [comment]
Similar behavior !

**Comment by briankariuki** [comment]
Got same crash today on emulator. Although the image gets saved to gallery

**Comment by MisakoGunjima** [comment]
I solved the problem by adding the following code to AndroidManifest.xml

`android:requestLegacyExternalStorage="true"`

**Comment by VOIDCRUSHER** [comment]
@MisakoGunjima  Are you on still on API 28? Crash persists on API 29 even with `android: requestLegacyExternalStorage="true"`

**Comment by kacank87** [comment]
i got same problem on android 11 . but if im using android version 10. its works.

**Comment by changalberto** [comment]
Is this still being maintained? Seems like the last commit was about 9 months ago.

**Comment by dancamdev** [comment]
It probably isn't, I came up with my own solution, I'll share as an article or package, I'm not sure yet 🙌

**Comment by Zchandev** [comment]
> It probably isn't, I came up with my own solution, I'll share as an article or package, I'm not sure yet 🙌

That would be awesome. Looking forward to your solution.

**Comment by YaoShuwei** [comment]
> @MisakoGunjima Are you on still on API 28? Crash persists on API 29 even with `android: requestLegacyExternalStorage="true"`
me too.

**Comment by jelenalecic** [comment]
hey all, please try the newest version and let me know if the issue still persists.
thanks!

**Comment by zanpen2000** [comment]
@jelenalecic Still happens to me, 

compileSdkVersion 29
minSdkVersion 21
targetSdkVersion 28
android: 11

**Comment by hajnalbendeguz** [comment]
Any updates on this? 
> Starting in November 2021, app updates will be required to target API level 30 or above

As stated on https://developer.android.com/
