### ISSUE TITLE
Type mismatch: inferred type is String? but String was expected

### ISSUE THREAD

**Issue by shofizone** [CarnegieTechnologies/gallery_saver#96]
`gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (280, 35): Type mismatch: inferred type is String? but String was expected`

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gallery_saver:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by dvaldivia** [comment]
Same problem

**Comment by devshisiyani** [comment]
Same problem

**Comment by YazeedAlKhalaf** [comment]
@CarnegieTech Any plans to fix this?

**Comment by dvaldivia** [comment]
I believe this is due to the null safety changes that are incoming, one we migrate out apps to null safety this problem will not matter

**Comment by shofizone** [comment]
No response form author. This error is coming from  native android part -> Kotlin. I have a simple fix for this problem, try this https://github.com/shofizone/gallery_saver.git

**Comment by lovemory** [comment]
e: F:\flutter\.pub-cache\hosted\pub.flutter-io.cn\gallery_saver-2.1.0\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (279, 35): Type mismatch: inferred type is String? but String was expected
e: F:\flutter\.pub-cache\hosted\pub.flutter-io.cn\gallery_saver-2.1.0\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (282, 35): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gallery_saver:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s

**Comment by lovemory** [comment]
pubspec.yaml  
gallery_saver: ^2.1.0
  image_picker: ^0.7.4

e: F:\flutter\.pub-cache\hosted\pub.flutter-io.cn\gallery_saver-2.1.0\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (279, 35): Type mismatch: inferred type is String? but String was expected
e: F:\flutter\.pub-cache\hosted\pub.flutter-io.cn\gallery_saver-2.1.0\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (282, 35): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gallery_saver:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s

**Comment by 5244santila** [comment]
I have the same issue. When attempting to revert to earlier stable versions, the null stability causes more trouble with other dependencies in my code.

**Comment by anhdhq** [comment]
I'm trying to save images and videos after take them from the camera to the device.

  camera: ^0.8.1
  video_player: ^2.1.1
  gallery_saver: ^2.1.0

e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-2.1.0\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (279, 35): Type mismatch: inferred type is String? but String was expected
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-2.1.0\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (282, 35): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gallery_saver:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         4.4s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by impliesiOS** [comment]
Launching lib/main.dart on POCO F1 in debug mode...
Running Gradle task 'assembleDebug'...
e: /Users/imac/Documents/K_Flutterr/flutter/.pub-cache/hosted/pub.dartlang.org/gallery_saver-2.1.0/android/src/main/kotlin/carnegietechnologies/gallery_saver/FileUtils.kt: (279, 35): Type mismatch: inferred type is String? but String was expected
e: /Users/imac/Documents/K_Flutterr/flutter/.pub-cache/hosted/pub.dartlang.org/gallery_saver-2.1.0/android/src/main/kotlin/carnegietechnologies/gallery_saver/FileUtils.kt: (282, 35): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gallery_saver:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1





in iOS its Works Perfectly But in android, it's Gate Same Issue Any idea to solve It? Thanks In Advance

**Comment by neroaCu** [comment]
Hi, I have the same issue.  It does not work even downgrade the version. help please.

**Comment by AlbusSong** [comment]
same problem...

**Comment by neroaCu** [comment]
for anyone who still struggle, you can try use this one https://pub.dev/packages/image_gallery_saver. It works for me.

**Comment by lecicdjuro** [comment]
done

**Comment by lAmirshahinxl** [comment]
just change your compileSdkVersion in build.gradle  :) 🌹

**Comment by Sreelakshmi192** [comment]
i changed sdk to 31 aand that gave err
