### ISSUE TITLE
Parameter albumName doesn't seem to be working

### ISSUE THREAD

**Issue by Tomucha** [CarnegieTechnologies/gallery_saver#98]
I'm trying to save photo into some "albumName":

        await GallerySaver.saveImage(f.absolute.path, albumName: "MyName");
        
But the file is just among other global photos, no folder or directory MyName is created. The file is plainly stored in "..../Pictures/filename.jpg".

Version 2.0.3, Google Pixel 2.

**Comment by tomXGames** [comment]
Same here. I tried changing the code in the FileUtils.kt file, but it doesn't seem to do anything.

**Comment by Hwan-seok** [comment]
I am facing this issue too. This should be fixed.
Related to #21.

**Comment by marcoberetta96** [comment]
The parameter `albumName` is not working yet in 2.1.0 version

**Comment by PairProgDominikaParaIstvanMunkacsi** [comment]
Adding android:requestLegacyExternalStorage="true" in AndroidManifest solved issue for me

**Comment by PairProgDominikaParaIstvanMunkacsi** [comment]
Adding android:requestLegacyExternalStorage="true" in AndroidManifest solved issue for me

**Comment by marcoberetta96** [comment]
@PairProgDominikaParaIstvanMunkacsi were you able to save images in a custom album on both Android and iOS?

**Comment by PairProgDominikaParaIstvanMunkacsi** [comment]
> @PairProgDominikaParaIstvanMunkacsi were you able to save images in a custom album on both Android and iOS?

Mentioned fix resolves the issue for Android. It has nothing to do with iOS since AndroidManifest is an Android-specific file. If you experience issues with saving to custom folder on iOS there should be another fix

**Comment by marcoberetta96** [comment]
@istvmunkacsi I only wish to know if you successfully tried to do the same thing also on iOS or if you experienced some issue.
Thank you

**Comment by Tomucha** [comment]
I believe this issue concerns Android only, albumName worked properly for me on iOS.

**Comment by marcoberetta96** [comment]
thanks for your answer

**Comment by venzeo** [comment]
Still an issue for Android in version of the plugin 2.1.3 
The gallery is called "Pictures" and contains only photos created within this plugin. On iOS it works without problems and it names it "AnyNameWeNeed". Thank you in advance for the fix.

**Comment by adamdupuis** [comment]
This issue is due to changes in the Android SDK. As @istvmunkacsi mentioned above, you need to add `android:requestLegacyExternalStorage="true"` to `AndroidManifest.xml`. It should look something like this:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.package.example">
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    <application
      android:name=".Application"
      android:label="App Name"
      android:requestLegacyExternalStorage="true">

      ...

    </application>
</manifest>
```

This fixed the issue for me on Android.
