### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by peterscodee** [CarnegieTechnologies/gallery_saver#99]
This is a request to add support for null safety to this package. See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by Johann-Hagen** [comment]
Is this package open to pull requests? I need this updated ASAP and I'll help migrating it if needed.

**Comment by AhmetMelihSerter** [comment]
I migrated null safety. Use this until the main package passes.
[https://github.com/AhmetMelihSerter/gallery_saver](url)

**Comment by lecicdjuro** [comment]
done
